name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
      - users: actions/seetup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v
